### Variables
@baseUrl = http://localhost:3000
@contentType = application/json

###############################################
# Register User
###############################################

# @name register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "username": "johndoe",
  "email": "john1@example.com",
  "password": "Nokia12@"
}

### Store created ID from response
@createdUserId = ""

###############################################
# Sign in User
###############################################

# @name signIn
POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "email": "john1@example.com",
  "password": "Nokia12@"
}

###############################################
# READ ALL (GET)
###############################################

GET {{baseUrl}}/users

### Query parameters & pagination
GET {{baseUrl}}/users?page=1&limit=10&search=john

###############################################
# READ ONE (GET)
###############################################

GET {{baseUrl}}/users/{{createdUserId}}

###############################################
# UPDATE FULL (PUT)
###############################################

PUT {{baseUrl}}/users/{{createdUserId}}
Content-Type: {{contentType}}

{
  "username": "johndoe_updated",
  "email": "john.updated@example.com",
}

###############################################
# UPDATE PARTIAL (PATCH)
###############################################

PATCH {{baseUrl}}/users/{{createdUserId}}
Content-Type: {{contentType}}

{
	"username": "johndoe_updated"
}

###############################################
# DELETE (DELETE)
###############################################

DELETE {{baseUrl}}/users/{{createdUserId}}